//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AutoResourceFile", typeof(AutoResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This brand is not configured for {0}..
        /// </summary>
        public static string BrandNotConfiguredFor {
            get {
                return ResourceManager.GetString("BrandNotConfiguredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDbContextFactory.Create(string): Connection string: &apos;{0}&apos;..
        /// </summary>
        public static string ConnectionStringCreate {
            get {
                return ResourceManager.GetString("ConnectionStringCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string &apos;{0}&apos; is null or empty..
        /// </summary>
        public static string ConnectionStringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ConnectionStringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currenty only cars search is supported.
        /// </summary>
        public static string CurrentlyOnlyCarsSearchIsSupported {
            get {
                return ResourceManager.GetString("CurrentlyOnlyCarsSearchIsSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only models under the same brand can be used for search criteria..
        /// </summary>
        public static string OnlyModelsUnderTheSameBrandCanBeUsedForSearchCriteria {
            get {
                return ResourceManager.GetString("OnlyModelsUnderTheSameBrandCanBeUsedForSearchCriteria", resourceCulture);
            }
        }
    }
}
